using AdventOfCode._01;
using AdventOfCode._02;
using AdventOfCode._03;
using AdventOfCode._04;
using AdventOfCode._05;
using AdventOfCode._06;
using AdventOfCode._07;
using AdventOfCode._08;
using AdventOfCode._09;
using AdventOfCode._10;
using AdventOfCode._11;
using AdventOfCode._12;
using AdventOfCode._13;
using AdventOfCode._14;
using AdventOfCode._15;
using AdventOfCode._16;
using AdventOfCode._17;
using AdventOfCode._18;
using AdventOfCode._19;
using AdventOfCode._20;

// await Trebuchet.MainAsync();
// await CubeConundrum.MainAsync();
// await GearRatios.MainAsync();
// await Scratchcards.MainAsync();
// await Fertilizer.MainAsync();
// await BoatRace.MainAsync();
// await CamelCards.MainAsync();
// await Wasteland.MainAsync();
// await Mirage.MainAsync();
// await PipeMaze.MainAsync();
// await CosmicExpansion.MainAsync();
// await HotSprings.MainAsync();
// await Incidence.MainAsync();
// await ReflectorDish.MainAsync();
// await LensLibrary.MainAsync();
// await LavaFloor.MainAsync();
// await ClumsyCrucible.MainAsync();
// await LavaductLagoon.MainAsync();
// await Aplenty.MainAsync();
await PulsePropagation.MainAsync();